use std::env;
use std::fs;
use std::path::PathBuf;

pub(crate) fn generate() {
    const BOARD_IMAGES: &[(&str, &str)] = &[
        ("HELTEC_V4", "heltec-v4.webp"),
        ("T_BEAM_SUPREME", "t-beam-supreme.webp"),
        ("XIAO_ESP32_C6", "xiao-esp32-c6.webp"),
        ("T_ECHO", "t-echo.webp"),
        (
            "SEEED_CARD_TRACKER_T1000_E",
            "seeed-card-tracker-t1000-e.webp",
        ),
        ("T114", "t114.webp"),
        ("HELTEC_MESH_NODE_T096", "heltec-mesh-node-t096.webp"),
        ("MESH_TOWER_V2", "mesh-tower-v2.webp"),
    ];

    let mut generated =
        String::from("// @generated by build.rs; do not edit.\nuse super::BoardImage;\n\n");
    for (ident, file_name) in BOARD_IMAGES {
        let asset_path = PathBuf::from("src")
            .join("assets")
            .join("boards")
            .join(file_name);
        println!("cargo:rerun-if-changed={}", asset_path.display());
        let bytes = fs::read(&asset_path).unwrap_or_else(|err| {
            panic!(
                "failed to read board image asset {}: {err}",
                asset_path.display()
            )
        });
        let data_uri = format!("data:image/webp;base64,{}", base64_encode(&bytes));
        generated.push_str(&format!(
            "pub static {ident}: BoardImage = BoardImage {{ data_uri: \"{data_uri}\" }};\n",
        ));
    }

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo");
    fs::write(PathBuf::from(out_dir).join("board_images.rs"), generated)
        .expect("failed to write generated board image module");
}

fn base64_encode(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    let mut encoded = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0];
        let b1 = chunk.get(1).copied().unwrap_or(0);
        let b2 = chunk.get(2).copied().unwrap_or(0);

        encoded.push(TABLE[(b0 >> 2) as usize] as char);
        encoded.push(TABLE[(((b0 & 0b0000_0011) << 4) | (b1 >> 4)) as usize] as char);
        if chunk.len() > 1 {
            encoded.push(TABLE[(((b1 & 0b0000_1111) << 2) | (b2 >> 6)) as usize] as char);
        } else {
            encoded.push('=');
        }
        if chunk.len() > 2 {
            encoded.push(TABLE[(b2 & 0b0011_1111) as usize] as char);
        } else {
            encoded.push('=');
        }
    }

    encoded
}
