use std::env;
use std::fs;
use std::path::PathBuf;

use prns_flash_manifest::{
    board_catalog, BoardAvailability, BoardBuild, BoardCatalogEntry, Transport, Uf2BoardIdMatchKind,
};

pub(crate) fn generate() {
    println!("cargo:rerun-if-changed=../../release/flash/boards.json");
    let catalog = board_catalog().unwrap_or_else(|error| {
        panic!("shared board catalog is invalid: {error}");
    });
    let mut generated = String::from(
        "// @generated by build.rs from release/flash/boards.json; do not edit.\n\
         use prns_flash_manifest::Uf2BoardIdMatchKind;\n\
         use super::{BoardFlashTarget, BoardTarget, NrfManagedApplicationIdentity, Uf2BoardIdentityRule, PreparationProfile, Tier, ESPRESSIF_NATIVE_USB_VENDOR_ID, SILICON_LABS_USB_VENDOR_ID};\n\n\
         pub const SHIPPING_BOARD_TARGETS: &[BoardTarget] = &[\n",
    );
    for board in catalog.shipping_boards() {
        let preparation_profile = preparation_profile(board);
        let flash_target = flash_target(board);
        generated.push_str("    BoardTarget {\n");
        generated.push_str(&format!("        name: {:?},\n", board.display_name));
        generated.push_str(&format!("        slug: {:?},\n", board.slug));
        generated.push_str(&format!("        silicon: {:?},\n", board.silicon));
        generated.push_str("        tier: Tier::Flashable,\n");
        generated.push_str("        interfaces: &[\n");
        for interface in &board.interfaces {
            generated.push_str(&format!("            {:?},\n", interface));
        }
        generated.push_str("        ],\n");
        generated.push_str(&format!("        icon: Some({:?}),\n", board.icon));
        generated.push_str(&format!(
            "        preparation_profile: Some({preparation_profile}),\n"
        ));
        generated.push_str(&format!("        flash_target: Some({flash_target}),\n"));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    generated.push_str("\npub const QUALIFICATION_BOARD_TARGETS: &[BoardTarget] = &[\n");
    for board in catalog
        .boards
        .iter()
        .filter(|board| board.availability == BoardAvailability::Qualification)
    {
        generated.push_str("    BoardTarget {\n");
        generated.push_str(&format!("        name: {:?},\n", board.display_name));
        generated.push_str(&format!("        slug: {:?},\n", board.slug));
        generated.push_str(&format!("        silicon: {:?},\n", board.silicon));
        generated.push_str("        tier: Tier::Qualification,\n");
        generated.push_str("        interfaces: &[\n");
        for interface in &board.interfaces {
            generated.push_str(&format!("            {:?},\n", interface));
        }
        generated.push_str("        ],\n");
        generated.push_str(&format!("        icon: Some({:?}),\n", board.icon));
        let preparation_profile = preparation_profile(board);
        let flash_target = flash_target(board);
        generated.push_str("        #[cfg(feature = \"local-dev-flasher\")]\n");
        generated.push_str(&format!(
            "        preparation_profile: Some({preparation_profile}),\n"
        ));
        generated.push_str("        #[cfg(not(feature = \"local-dev-flasher\"))]\n");
        generated.push_str("        preparation_profile: None,\n");
        generated.push_str("        #[cfg(feature = \"local-dev-flasher\")]\n");
        generated.push_str(&format!("        flash_target: Some({flash_target}),\n"));
        generated.push_str("        #[cfg(not(feature = \"local-dev-flasher\"))]\n");
        generated.push_str("        flash_target: None,\n");
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo");
    fs::write(PathBuf::from(out_dir).join("shipping_boards.rs"), generated)
        .expect("failed to write generated shipping board catalog");
}

fn preparation_profile(board: &BoardCatalogEntry) -> &'static str {
    match board.preparation_profile.as_str() {
        "esp-usb-boot" => "PreparationProfile::EspUsbBoot",
        "techo-uf2" => "PreparationProfile::TechoUf2",
        "t114-uf2" => "PreparationProfile::T114Uf2",
        "mesh-pocket-uf2" => "PreparationProfile::MeshPocketUf2",
        "wio-tracker-l1-uf2" => "PreparationProfile::WioTrackerL1Uf2",
        "mesh-tower-v2-uf2" => "PreparationProfile::MeshTowerV2Uf2",
        "muzi-base-duo-uf2" => "PreparationProfile::MuziBaseDuoUf2",
        "t096-uf2" => "PreparationProfile::T096Uf2",
        "rak4631-uf2" => "PreparationProfile::Rak4631Uf2",
        "rak10724-uf2" => "PreparationProfile::Rak10724Uf2",
        "sensecap-solar-node-uf2" => "PreparationProfile::SensecapSolarNodeUf2",
        "t1000e-nrf-dfu" => "PreparationProfile::T1000eNrfSerialDfu",
        value => panic!("unsupported website preparation profile {value:?}"),
    }
}

fn flash_target(board: &BoardCatalogEntry) -> String {
    match (&board.transport, &board.build) {
        (Transport::EspSerial, BoardBuild::Esp(_)) => {
            let expected_chip = board
                .expected_chip
                .as_deref()
                .expect("validated ESP catalog target has a chip family");
            let vendor_id = match board.slug.as_str() {
                "heltec-v3" => "SILICON_LABS_USB_VENDOR_ID",
                _ => "ESPRESSIF_NATIVE_USB_VENDOR_ID",
            };
            format!(
                "BoardFlashTarget::EspSerial {{ expected_chip: {expected_chip:?}, web_serial_vendor_id: {vendor_id}, supports_provisioning: {}, supports_tcp_client_provisioning: {} }}",
                board.supports_provisioning(),
                board.supports_tcp_client_provisioning()
            )
        }
        (Transport::Uf2MassStorage, BoardBuild::Uf2(build)) => uf2_flash_target(
            &build.mount_label,
            build.board_identity.match_kind,
            &build.board_identity.value,
            &build.alternative_board_identities,
        ),
        (Transport::NrfSerialDfu, BoardBuild::NrfSerialDfu(build)) => {
            let match_kind = match build.recovery.board_identity.match_kind {
                Uf2BoardIdMatchKind::Exact => "Uf2BoardIdMatchKind::Exact",
                Uf2BoardIdMatchKind::ExactShared => "Uf2BoardIdMatchKind::ExactShared",
                Uf2BoardIdMatchKind::RevisionPrefix => "Uf2BoardIdMatchKind::RevisionPrefix",
            };
            let serial = build
                .serial
                .clone()
                .into_validated()
                .unwrap_or_else(|error| {
                    panic!("catalog Nordic serial transport is invalid: {error}")
                });
            let managed_usb = serial.managed_application_usb();
            format!(
                "BoardFlashTarget::NrfSerialDfu {{ recovery_mount_label: {:?}, recovery_board_id_match_kind: {match_kind}, recovery_board_id: {:?}, managed_application: NrfManagedApplicationIdentity {{ vendor_id: {:#06x}, product_id: {:#06x}, manufacturer: {:?}, product: {:?}, serial_number: {:?}, interface_number: {} }} }}",
                build.recovery.mount_label,
                build.recovery.board_identity.value,
                managed_usb.vendor_id(),
                managed_usb.product_id(),
                serial.managed_application_manufacturer(),
                serial.managed_application_product(),
                serial.managed_application_serial_number(),
                serial.managed_application_interface_number()
            )
        }
        _ => panic!("validated catalog transport and build recipe disagree"),
    }
}

fn uf2_flash_target(
    mount_label: &str,
    board_id_match_kind: Uf2BoardIdMatchKind,
    board_id: &str,
    alternatives: &[prns_flash_manifest::Uf2BoardIdentity],
) -> String {
    let match_kind = match board_id_match_kind {
        Uf2BoardIdMatchKind::Exact => "Uf2BoardIdMatchKind::Exact",
        Uf2BoardIdMatchKind::ExactShared => "Uf2BoardIdMatchKind::ExactShared",
        Uf2BoardIdMatchKind::RevisionPrefix => "Uf2BoardIdMatchKind::RevisionPrefix",
    };
    let alternatives = alternatives
        .iter()
        .map(|identity| {
            format!(
                "Uf2BoardIdentityRule {{ kind: Uf2BoardIdMatchKind::{:?}, value: {:?} }}",
                identity.match_kind, identity.value
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "BoardFlashTarget::Uf2MassStorage {{ mount_label: {mount_label:?}, board_id_match_kind: {match_kind}, board_id: {board_id:?}, alternative_board_identities: &[{alternatives}] }}"
    )
}
