APPLICATION_FLASH_ORIGIN = 0x00027000;
APPLICATION_FLASH_END = 0x000EA000;
PERSISTENCE_FLASH_END = 0x000F0000;
NODE_IDENTITY_FLASH_ORIGIN = 0x000F0000;
RECOVERY_BOOTLOADER_FLASH_ORIGIN = 0x000F4000;
FLASH_PAGE_BYTES = 0x1000;
APPLICATION_FLASH_BYTES = APPLICATION_FLASH_END - APPLICATION_FLASH_ORIGIN;

APPLICATION_RAM_ORIGIN = 0x20010000;
NRF52840_RAM_END = 0x20040000;
APPLICATION_RAM_BYTES = NRF52840_RAM_END - APPLICATION_RAM_ORIGIN;
MIN_RUNTIME_STACK_BYTES = 68K;

MEMORY
{
  FLASH : ORIGIN = APPLICATION_FLASH_ORIGIN, LENGTH = APPLICATION_FLASH_BYTES
  RAM   : ORIGIN = APPLICATION_RAM_ORIGIN, LENGTH = APPLICATION_RAM_BYTES
}

ASSERT(
  APPLICATION_FLASH_END + 6 * FLASH_PAGE_BYTES == PERSISTENCE_FLASH_END,
  "T1000-E persistence journal must occupy the six pages after the application"
);

ASSERT(
  PERSISTENCE_FLASH_END == NODE_IDENTITY_FLASH_ORIGIN,
  "T1000-E persistence journal must end at node identity storage"
);

ASSERT(
  NODE_IDENTITY_FLASH_ORIGIN + 4 * FLASH_PAGE_BYTES == RECOVERY_BOOTLOADER_FLASH_ORIGIN,
  "T1000-E application data must end at the recovery bootloader"
)

ASSERT(
  ORIGIN(RAM) + LENGTH(RAM) - _stack_end >= MIN_RUNTIME_STACK_BYTES,
  "T1000-E static memory leaves too little runtime stack"
)
