APPLICATION_FLASH_ORIGIN = 0x00026000;
PERSISTENCE_FLASH_ORIGIN = 0x000E2000;
BLE_IDENTITY_FLASH_ORIGIN = 0x000E8000;
RADIO_PROFILE_FLASH_ORIGIN = 0x000E9000;
NODE_IDENTITY_FLASH_ORIGIN = 0x000EB000;
APPLICATION_DATA_END = 0x000EC000;
FACTORY_RESERVED_FLASH_ORIGIN = 0x000ED000;
RECOVERY_BOOTLOADER_FLASH_ORIGIN = 0x000F4000;
FLASH_PAGE_BYTES = 0x1000;
APPLICATION_FLASH_BYTES = PERSISTENCE_FLASH_ORIGIN - APPLICATION_FLASH_ORIGIN;

APPLICATION_RAM_ORIGIN = 0x2000E000;
NRF52840_RAM_END = 0x20040000;
APPLICATION_RAM_BYTES = NRF52840_RAM_END - APPLICATION_RAM_ORIGIN;
MIN_RUNTIME_STACK_BYTES = 68K;

MEMORY
{
  FLASH : ORIGIN = APPLICATION_FLASH_ORIGIN, LENGTH = APPLICATION_FLASH_BYTES
  RAM   : ORIGIN = APPLICATION_RAM_ORIGIN, LENGTH = APPLICATION_RAM_BYTES
}

ASSERT(
  PERSISTENCE_FLASH_ORIGIN + 6 * FLASH_PAGE_BYTES == BLE_IDENTITY_FLASH_ORIGIN,
  "T096 persistence journal must occupy the six pages before BLE identity storage"
);

ASSERT(
  BLE_IDENTITY_FLASH_ORIGIN + FLASH_PAGE_BYTES == RADIO_PROFILE_FLASH_ORIGIN,
  "T096 BLE identity must end at the radio-profile pages"
)

ASSERT(
  RADIO_PROFILE_FLASH_ORIGIN + 2 * FLASH_PAGE_BYTES == NODE_IDENTITY_FLASH_ORIGIN,
  "T096 radio-profile pages must end at the node identity"
)

ASSERT(
  NODE_IDENTITY_FLASH_ORIGIN + FLASH_PAGE_BYTES == APPLICATION_DATA_END,
  "T096 node identity must end at the application-data boundary"
)

ASSERT(
  APPLICATION_DATA_END + FLASH_PAGE_BYTES == FACTORY_RESERVED_FLASH_ORIGIN,
  "T096 guard page must precede Heltec factory data"
)

ASSERT(
  FACTORY_RESERVED_FLASH_ORIGIN < RECOVERY_BOOTLOADER_FLASH_ORIGIN,
  "T096 factory data must remain below the recovery bootloader"
)

ASSERT(
  ORIGIN(RAM) + LENGTH(RAM) - _stack_end >= MIN_RUNTIME_STACK_BYTES,
  "T096 static memory leaves too little runtime stack"
)
