#!/bin/sh /etc/rc.common

START=18
STOP=9
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /etc/hopspot/manager \
		--root /etc/hopspot \
		--max-compressed-bytes 2097152 --max-executable-bytes 4194304 \
		--flash-reserve-bytes 262144 --ram-reserve-bytes 8388608 \
		radio watch
	procd_set_param respawn 60 2 3
	procd_set_param term_timeout 2
	procd_set_param limits nofile="64 64" core="0 0"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
