#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /etc/hopspot/manager \
		--root /etc/hopspot \
		--max-compressed-bytes 2097152 --max-executable-bytes 4194304 \
		--flash-reserve-bytes 262144 --ram-reserve-bytes 8388608 \
		run --config /etc/hopspot/config.json --ram-directory /tmp/hopspot
	procd_set_param respawn 60 2 3
	procd_set_param term_timeout 15
	procd_set_param limits nofile="128 128" core="0 0"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
