/* auto-generated by NAPI-RS */
/* eslint-disable */

export type InterfaceKindName =
  | 'loopback' | 'tcp-client' | 'tcp-server' | 'udp' | 'serial'
  | 'usb-auto-host' | 'usb-auto-device' | 'auto-wifi' | 'wifi-peer'
  | 'local-server' | 'local-client' | 'tcp-server-peer' | 'bluetooth-auto'
  | 'bluetooth-peer' | 'lora' | 'kiss' | 'ax25-kiss' | 'pipe' | 'rnode'
  | 'backbone-server' | 'backbone-server-peer' | 'backbone-client' | 'esp-now'
  | 'websocket-client' | 'websocket-server' | 'websocket-server-peer'
  | 'wifi-direct' | 'wifi-direct-peer' | 'wifi-aware' | 'wifi-aware-peer'
  | 'i2p' | 'i2p-peer' | 'weave' | 'weave-peer'
export type ConnectionStateName = 'initializing' | 'connected' | 'degraded' | 'reconnecting' | 'failed' | 'disconnected' | 'disabled' | 'unknown'
export type DeliveryEvidenceName = 'proofExplicit' | 'proofImplicit' | 'response'
export type ProofStrategyName = 'proveAll' | 'proveNone' | 'proveIf'
export type LinkRequestPolicyName = 'acceptAll' | 'acceptNone'
export type RatchetPolicyName = 'noRatchets' | 'ratcheted' | 'ratchetsRequired'
export type RequestPolicyName = 'allowAll' | 'allowNone' | 'allowList'
export type ResourceAcceptName = 'none' | 'all' | 'if'
export type CompressionName = 'auto' | 'never'
export type BlackholeOutcomeName = 'added' | 'alreadyPresent'
export type UnblackholeOutcomeName = 'removed' | 'notFound'
export type MarkDestinationUsedOutcomeName = 'recorded' | 'refreshed' | 'retained' | 'notFound'
export type RetainDestinationOutcomeName = 'retained' | 'alreadyRetained' | 'notFound'
export type ReleaseDestinationOutcomeName = 'released' | 'useRecorded' | 'useRefreshed' | 'notFound'
export type LinkClosedReasonName = 'timeout' | 'peerClosed' | 'malformedRtt'

export type PrnsNodeEvent =
  | { type: 'announce'; appData: Buffer; destination: Buffer; hops: number; sourceInterface: Buffer }
  | { type: 'singleDelivery'; destination: Buffer; plaintext: Buffer; sourceInterface: Buffer }
  | { type: 'linkDelivery'; linkId: Buffer; plaintext: Buffer; sourceInterface: Buffer }
  | { type: 'request'; destination: Buffer; linkId: Buffer; requestId: Buffer; requester?: Buffer; pathHash: Buffer; rttMillis: number; data: Buffer; token: RespondTokenSpec }
  | { type: 'response'; linkId: Buffer; requestId: Buffer; data: Buffer }
  | { type: 'responseSegment'; linkId: Buffer; requestId: Buffer; segmentIndex: number; totalSegments: number; data: Buffer }
  | { type: 'resourceReceived'; linkId: Buffer; hash: Buffer; metadata?: Buffer; data: Buffer }
  | { type: 'resourceSegment'; linkId: Buffer; originalHash: Buffer; segmentIndex: number; totalSegments: number; metadata?: Buffer; data: Buffer }
  | { type: 'channelMessage'; linkId: Buffer; messageType: number; data: Buffer }
  | { type: 'linkEstablished'; linkId: Buffer; rttMillis: number }
  | { type: 'peerIdentified'; linkId: Buffer; identity: Buffer }
  | { type: 'linkClosed'; linkId: Buffer; reason: LinkClosedReasonName }
  | { type: 'commandSettled'; id: number; settlement: string }
  | { type: 'selfRatchetRotated'; destination: Buffer }
  | { type: 'announceHeldDropped'; destination: Buffer; sourceInterface: Buffer; cause: string }
  | { type: 'linkInterfaceMismatch'; linkId: Buffer; attachedInterface: Buffer; arrivedOn: Buffer }
  | { type: 'resourceAssembled'; linkId: Buffer; originalHash: Buffer; totalSizeBytes: bigint }
  | { type: 'resourceFailed'; linkId: Buffer; hash: Buffer; cause: string }
  | { type: 'resourceSendProgress'; linkId: Buffer; transferredBytes: bigint; totalBytes: bigint; physicalTransferredBytes: bigint; segmentIndex: number; totalSegments: number }
  | { type: 'routeExpired' | 'routeEvicted' | 'routeInterfaceGone' | 'routeDropped'; destination: Buffer }
  | { type: 'persistenceRestored'; routes: number; destinationIdentities: number; tunnels: number; ratchets: number; refused: number; dropped: number }
  | { type: 'persistenceFlushed'; cause: 'startup' | 'interval' | 'routeChange' | 'ratchetRotation' | 'shutdown'; target: 'routingState' | 'ratchets' }
  | { type: 'persistenceFlushFailed'; cause: 'startup' | 'interval' | 'routeChange' | 'ratchetRotation' | 'shutdown'; target: 'routingState' | 'ratchets' }
  | { type: 'delivered' | 'message'; detail: string }
  | { type: 'eventOverflow'; droppedDiagnostics: number }
  | { type: 'eventBackpressureExceeded'; rejectedEventBytes: number }
  | { type: 'nodeStopped'; cause: string }
export declare class InterfaceHandle {
  get id(): Buffer
  get kind(): string | null
  teardown(): boolean
}

export declare class PrnsNode {
  get identityHash(): Buffer
  get destinationHashes(): Array<Buffer>
  ready(): Promise<void>
  stop(): Promise<void>
  announce(destination: Buffer, options?: AnnounceOptions | undefined | null): Promise<void>
  sendSinglePacket(destination: Buffer, data: Buffer): Promise<PacketReceipt>
  sendLinkPacket(linkId: Buffer, data: Buffer): Promise<PacketReceipt>
  sendChannelMessage(linkId: Buffer, messageType: number, data: Buffer): Promise<PacketReceipt>
  establishLink(destination: Buffer): Promise<Buffer>
  establishLinkWithRtt(destination: Buffer): Promise<LinkInfo>
  closeLink(linkId: Buffer): boolean
  requestPath(destination: Buffer): Promise<PathInfo>
  identify(linkId: Buffer, identity: Buffer): Promise<void>
  request(linkId: Buffer, pathHash: Buffer, data: Buffer, options?: RequestOptions | undefined | null): Promise<RequestResult>
  respond(token: RespondTokenSpec, data: Buffer): Promise<number>
  respondFile(token: RespondTokenSpec, path: string): Promise<number>
  allowRequester(destination: Buffer, pathHash: Buffer, identity: Buffer): Promise<void>
  attachTcpServer(options: TcpServerOptions): Promise<InterfaceHandle>
  attachTcpClient(options: TcpClientOptions): Promise<InterfaceHandle>
  attachUdp(options: UdpOptions): Promise<InterfaceHandle>
  attachInterface(config: InterfaceConfigSpec, routing?: InterfaceRoutingPolicySpec | undefined | null): Promise<InterfaceHandle>
  previewValidateInterfaceConfig(spec: InterfaceConfigSpec): string
  attachSharedInstanceServer(options?: SharedInstanceOptions | undefined | null): Promise<InterfaceHandle>
  attachSharedInstanceClient(options?: SharedInstanceOptions | undefined | null): Promise<InterfaceHandle>
  attachConfig(configText: string): Promise<ConfigAttachResult>
  attachAutoWifi(): InterfaceHandle
  attachAutoUsb(options?: AutoUsbOptions | undefined | null): InterfaceHandle
  attachAutoBluetoothLe(options: AutoBluetoothLeOptions): InterfaceHandle
  sendResource(linkId: Buffer, data: Buffer, options?: SendResourceOptions | undefined | null): Promise<void>
  sendResourceFile(linkId: Buffer, path: string, options?: SendResourceOptions | undefined | null): Promise<void>
  receiveResource(linkId: Buffer): Promise<ResourceData>
  receiveResourceFile(linkId: Buffer, path: string): Promise<ResourceFileReceipt>
  setResourceStrategy(destination: Buffer, strategy: ResourceStrategySpec): Promise<boolean>
  setLinkResourceStrategy(linkId: Buffer, strategy: ResourceStrategySpec): Promise<void>
  interfaces(): Array<InterfaceInfo>
  interfaceInventory(): Array<InterfaceInventoryInfo>
  hostSnapshot(): Promise<HostSnapshotInfo>
  linkCount(): Promise<number>
  routes(): Promise<RouteInfo[]>
  route(destination: Buffer): Promise<RouteInfo | null>
  announceRates(): Promise<AnnounceRateInfo[]>
  destinationIdentityHash(destination: Buffer): Promise<Buffer | null>
  destinationIdentity(query: DestinationIdentityQuerySpec): Promise<DestinationIdentityInfo | null>
  dropRoute(destination: Buffer): Promise<boolean>
  dropRoutesVia(transportId: Buffer): Promise<number>
  clearAnnounceQueues(): Promise<number>
  blackholeIdentity(identity: Buffer, reason?: string | undefined | null): Promise<BlackholeOutcomeName>
  unblackholeIdentity(identity: Buffer): Promise<UnblackholeOutcomeName>
  blackholedIdentities(): Promise<BlackholedIdentityInfo[]>
  isBlackholed(identity: Buffer): Promise<boolean>
  markDestinationUsed(destination: Buffer): Promise<MarkDestinationUsedOutcomeName>
  retainDestination(destination: Buffer): Promise<RetainDestinationOutcomeName>
  releaseDestination(destination: Buffer): Promise<ReleaseDestinationOutcomeName>
  retainIdentity(identity: Buffer): Promise<RetainIdentityResult>
}

export interface AnnounceOptions {
  interfaceId?: Buffer
}

export interface AnnounceRateInfo {
  destination: Buffer
  lastAllowedAnnounceAtMillis: number
  blockedUntilMillis: number
  observedAtMillis: Array<number>
  rateViolations: number
}

export interface AutoBluetoothLeOptions {
  identityPath?: string
  identitySecret?: Buffer
}

export interface AutoUsbOptions {
  baud?: number
}

export declare function backendInfo(): BackendInfo

export interface BackendInfo {
  backend: string
  capabilities: Array<string>
  interfaceKinds: Array<string>
}

export interface BlackholedIdentityInfo {
  identity: Buffer
  source: Buffer
  reason?: string
  indefinite: boolean
}

export interface ConfigAttachment {
  name: string
  id: Buffer
}

export interface ConfigAttachResult {
  attached: Array<ConfigAttachment>
  failures: Array<ConfigFailure>
  warnings: Array<string>
}

export interface ConfigFailure {
  name: string
  error: string
}

export interface DestinationIdentityInfo {
  destination: Buffer
  identity: Buffer
  publicKey: Buffer
}

export interface DestinationIdentityQuerySpec {
  destination?: Buffer
  identity?: Buffer
}

export interface DestinationSpec {
  appName: string
  aspects: Array<string>
  kind?: 'single' | 'plain'
  identity?: IdentitySpec
  useHostIdentity?: boolean
  announceAppData?: Buffer
  maximumRequestBytes?: number
  proof?: ProofStrategyName
  linkRequests?: LinkRequestPolicyName
  ratchet?: RatchetPolicyName
  resourceStrategy?: ResourceStrategySpec
  requestPaths?: Array<RequestPathSpec>
}

export declare function generateIdentitySecret(): Buffer

export declare function hostContractAbi(): number

export interface HostDestinationIdentitySnapshotInfo {
  destination: Buffer
  identity: Buffer
}

export interface HostInterfaceSnapshotInfo {
  interfaceId: Buffer
  name?: string
  kind?: string
  health: string
  failureDetail?: string
  rxBytes: bigint
  txBytes: bigint
  rxBps?: number
  txBps?: number
  routeCount: number
  linkCount: number
  transportedLinkCount: number
}

export interface HostPersistenceSnapshotInfo {
  persistent: boolean
  restored: boolean
  lastFlushCause?: string
  lastFailureDetail?: string
}

export interface HostRouteSnapshotInfo {
  destination: Buffer
  hops: number
  viaIdentity?: Buffer
  interfaceId: Buffer
  learnedAtMillis: number
  lastRouteActivityAtMillis: number
  expiresAtMillis: number
}

export interface HostRuntimeHealthSnapshotInfo {
  running: boolean
  uptimeMillis: number
  interfaceCount: number
  onlineInterfaceCount: number
  routeCount: number
  linkCount: number
  transportedLinkCount: number
  rxBytes: bigint
  txBytes: bigint
  rxBps: number
  txBps: number
}

export declare function hostSchemaVersion(): number

export interface HostSnapshotInfo {
  revision: bigint
  backend: BackendInfo
  interfaces: Array<HostInterfaceSnapshotInfo>
  routes: Array<HostRouteSnapshotInfo>
  activeLinkCount: number
  destinationIdentities: Array<HostDestinationIdentitySnapshotInfo>
  runtime: HostRuntimeHealthSnapshotInfo
  persistence: HostPersistenceSnapshotInfo
}

export interface IdentitySpec {
  secret?: Buffer
  path?: string
}

export interface InterfaceConfigSpec {
  kind: string
  groupId?: string
  discoveryScope?: string
  discoveryPort?: number
  dataPort?: number
  devices?: Array<string>
  ignoredDevices?: Array<string>
  multicastAddressType?: string
  target?: string
  bind?: string
  local?: string
  peer?: string
  bitrateBps?: number
  port?: string
  line?: SerialLineSpec
  flowControl?: boolean
  preambleMillis?: number
  transmitTailMillis?: number
  persistence?: number
  slotTimeMillis?: number
  stationCallsign?: string
  stationIntervalSeconds?: number
  callsign?: string
  ssid?: number
  radio?: RNodeRadioSpec
  airtimeLimitShortCentiPercent?: number
  airtimeLimitLongCentiPercent?: number
  members?: Array<MultiRNodeMemberSpec>
  command?: Array<string>
  respawnDelayMillis?: number
  peers?: Array<string>
  connectable?: boolean
  url?: string
  framing?: 'RawPacket' | 'Hdlc' | 'Kiss' | 'Auto'
}

export interface InterfaceInfo {
  id: Buffer
  kind?: InterfaceKindName
  connection: ConnectionStateName
  failureReason?: string
  rxBytes: bigint
  txBytes: bigint
  rxBps?: number
  txBps?: number
  destinations: number
  links: number
  transportedLinks: number
  supervisorId?: Buffer
}

export interface InterfaceInventoryInfo {
  name?: string
  origin: string
  interface: InterfaceInfo
}

export interface InterfaceRoutingPolicySpec {
  mode?: string
  gravity?: number
  recursivePathRequests?: boolean
  announcesFromInternal?: boolean
  announcesToInternal?: boolean
}

export interface LinkInfo {
  linkId: Buffer
  rttMillis: number
}

export interface MultiRNodeMemberSpec {
  name: string
  virtualPort: number
  radio: RNodeRadioSpec
  flowControl: boolean
  outgoing: boolean
}

export interface NodeOptions {
  identity?: IdentitySpec
  role?: 'endpoint' | 'transport'
  destinations?: Array<DestinationSpec>
  eventQueueLimit?: number
  applicationEventQueueLimit?: number
  retainedEventBytesLimit?: number
  diagnosticEventQueueLimit?: number
  persistencePath?: string
}

export interface PacketReceipt {
  rttMillis: number
  evidence: DeliveryEvidenceName
  packetHash?: Buffer
}

export interface PathInfo {
  hops: number
}

export interface RequestOptions {
  /** Request timeout in milliseconds. */
  timeoutMillis?: number
  maximumResponseBytes?: number
}

export declare function requestPathHash(path: string): Buffer

export interface RequestPathSpec {
  path: string
  policy?: RequestPolicyName
}

export interface RequestResult {
  data: Buffer
  packed: Buffer
  rttMillis: number
}

export interface ResourceData {
  data: Buffer
  metadata?: Buffer
  originalHash: Buffer
  totalSizeBytes: bigint
}

export interface ResourceFileReceipt {
  metadata?: Buffer
  originalHash: Buffer
  totalSizeBytes: bigint
}

export interface ResourceStrategySpec {
  accept: ResourceAcceptName
  /** Maximum accepted uncompressed payload size in bytes. */
  maxUncompressedBytes?: number
  acceptCompressed?: boolean
}

export interface RespondTokenSpec {
  linkId: Buffer
  requestId: Buffer
  rttMillis: number
}

export interface RetainIdentityResult {
  newlyRetainedDestinationCount: number
  alreadyRetainedDestinationCount: number
}

export interface RNodeRadioSpec {
  frequencyHz: number
  bandwidthHz: number
  txPowerDbm: number
  spreadingFactor: number
  codingRate: number
}

export interface RouteInfo {
  destination: Buffer
  hops: number
  via?: Buffer
  interfaceId: Buffer
  learnedAtMillis: number
  lastRouteActivityAtMillis: number
  expiresAtMillis: number
}

export interface SendResourceOptions {
  metadata?: Buffer
  compression?: CompressionName
  progress?: boolean
}

export interface SerialLineSpec {
  baud: number
  dataBits: string
  parity: string
  stopBits: string
}

export interface SharedInstanceOptions {
  port?: number
}

export declare function startNode(options: NodeOptions, onEvent: (event: PrnsNodeEvent) => void): PrnsNode

export interface TcpClientOptions {
  target: string
  bitrateBps?: number
}

export interface TcpServerOptions {
  bind: string
  bitrateBps?: number
}

export interface UdpOptions {
  local: string
  peer: string
  bitrateBps?: number
}

export declare function version(): string
