[target.aarch64-apple-darwin]
rustflags = [
  "-L", "/Library/Developer/CommandLineTools/usr/lib/swift/macosx",
  "-C", "link-arg=-lswiftCompatibility56",
  "-C", "link-arg=-lswiftCompatibilityConcurrency",
]
